### ISSUE TITLE
What advantage does this have over the Container?

### ISSUE THREAD

**Issue by martinbean** [peyman3d/laravel-share#1]
I see this is essentially a singleton data store. What advantage does this have over properly using the Container, something else that can be passed—and accessed—everywhere in a Laravel application?

**Comment by p3yman** [comment]
Hi,
You absolutely can do that. But this package is about syntax and have a better & good looking code. As you can see in documents it includes many aliases for adding data and even you can manage this aliases for keys and fields.
The main idea was a solution for a problem that I had for sometime and I hope it help others to create better projects. 

Thanks a lot
